export enum ApplicationStatus {
  APPLIED = 'APPLIED',
  PENDING = 'PENDING',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  TECHNICAL_TEST = 'TECHNICAL_TEST',
  AWAITING_DECISION = 'AWAITING_DECISION',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  NEGOTIATION = 'NEGOTIATION',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  REJECTED_BY_COMPANY = 'REJECTED_BY_COMPANY',
  OFFER_DECLINED = 'OFFER_DECLINED',
  APPLICATION_WITHDRAWN = 'APPLICATION_WITHDRAWN',
}
